[filesystem]
stage = "dev/stage/"
deploy = "dev/deploy/ioc/"
shellbox = "dev/deploy/ioc/hosts/"

[app]
# can be a glob, e.g. "templates/**/*.tera"
#template_directory = "templates/**/*.tera"
template_directory = "/templates/**/*.tera"
