# system default configuration for production `ioc`
# this file is mandatory and needs to placed in `/opt/apps/ioc/config/`
[filesystem]
# stage_root = "${stage_prefix}/ioc/stage/"
stage = "XDG_RUNTIME_DIR"
deploy = "/opt/ioc/"
shellbox = "/opt/ioc/hosts/"

[app]
# can be a glob, e.g. "templates/**/*.tera"
template_directory = "/etc/ioc/templates/*.tera"
