---
- name: uninstall ioc-tool
  hosts: ioc-hosts
  become: true
  vars:
    ansible_remote_tmp: /tmp

  tasks:
  - name: Recursively remove /opt/apps/ioc
    ansible.builtin.file:
      path: /opt/apps/ioc
      state: absent
